# Generated by Django 5.0.6 on 2024-05-29 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Varillas', '0002_cliente_contacto_alter_varilla_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='nombre',
            field=models.PositiveIntegerField(editable=False, null=True, unique=True),
        ),
    ]
