# Generated by Django 5.0.6 on 2024-05-29 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Varillas', '0003_alter_venta_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='apellido',
            field=models.CharField(default='ApellidoDesconocido', max_length=255),
            preserve_default=False,
        ),
    ]
