# Generated by Django 5.0.6 on 2024-05-29 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Varillas', '0005_venta_cantidad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venta',
            old_name='cantidad',
            new_name='Metros',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='varilla',
        ),
        migrations.AddField(
            model_name='venta',
            name='varilla',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Varillas.varilla'),
        ),
    ]
