# Generated by Django 5.0.6 on 2024-05-29 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Varillas', '0007_alter_venta_metros'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='varilla',
        ),
        migrations.AddField(
            model_name='venta',
            name='varilla',
            field=models.ManyToManyField(to='Varillas.varilla'),
        ),
    ]
