# Generated by Django 5.0.6 on 2024-05-29 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Varillas', '0009_vidrio_venta_vidrio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passpartou',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
