# Generated by Django 5.0.6 on 2024-05-29 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Varillas', '0010_passpartou'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='passpartou',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Varillas.passpartou'),
        ),
    ]
