# Generated by Django 5.0.6 on 2024-05-30 00:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Varillas', '0011_venta_passpartou'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venta',
            old_name='Metros',
            new_name='Alto',
        ),
        migrations.AddField(
            model_name='venta',
            name='Ancho',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='venta',
            name='varilla',
        ),
        migrations.AddField(
            model_name='venta',
            name='varilla',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Varillas.varilla'),
        ),
    ]
